/// defines instructions
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Instruction {
    LdReg,
    LdImm,             
    Swp,            
    PushAddr,
    PushReg,            
    Pop,            
    Nop,            
    AddReg,
    AddImm,            
    SubReg,
    SubImm,          
    MulReg,
    MulImm,            
    AndReg,
    AndImm,            
    OrReg,
    OrImm,             
    XorReg,
    XorImm,            
    CmpReg,
    CmpImm,    
    MovDregSreg,    
    MovDregSimm,    
    MovDregSaddr,   
    MovDaddrSreg,   
    Hlt,            
    JmpAddr,        
    JmpImm,
    JmpReg,
    JeqReg,
    JeqImm,
    IntReg,
    IntImm
}
