[package]
name = "deadbolt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
clap = "2.33.3"
regex = "1"
getch = "0.3.1"

[package.release]
strip = "symbols"
